### ISSUE TITLE
Roads are extruded?

### ISSUE THREAD

**Issue by xuv** [hanbyul-here/tile-exporter#17]
Hello @hanbyul-here 

Not sure this is really an issue. But in the lastest version of the code, I I find it "strange" that roads are extruded. Is this the intended behavior?
See [this page for example](http://localhost:3000/?lon=-73.9709472656&lat=40.7805414319&zoom=16). This is central park. Screenshot here under.
![screen shot 2016-10-20 at 18 28 26](https://cloud.githubusercontent.com/assets/192539/19580250/0ac426ca-96f3-11e6-8ec8-f588860571d6.png)

Since you are actually hard working on the code. This might just be a transition artefact. I'm not sure.

**Comment by hanbyul-here** [comment]
Hi!
so I wanted to extrude roads for a long time, but I actually got it to work as a byproduct of upgrading to vector tile v1.0 😄  I think current extruding parameters are weird though (roads are too high!) , so just opened the pr to make more sense.

**Comment by xuv** [comment]
Hey. Great :) Indeed it could be nice to have options to decide wether someone might want to add road, buildings or else... And maybe tweek their height :) It could produce interesting results :)

**Comment by hanbyul-here** [comment]
I do agree with you! it is actually not tricky to do, but I was bit lazy about building UI ! I will def consider building UI about it on next turn.
