### ISSUE TITLE
can't run locally with Node 6.0

### ISSUE THREAD

**Issue by hanbyul-here** [hanbyul-here/tile-exporter#6]
- can't run locally 😢

**Comment by xuv** [comment]
Running node v6.3.1, I'm getting:  
`ERROR in Path must be a string. Received undefined`  
Do you get the same error?

**Comment by hanbyul-here** [comment]
@xuv Yes I am getting the same error . I am working around using node v5.0

**Comment by xuv** [comment]
@hanbyul-here Thx. Trying to find out where that error might be from. But I have no clue where to start. :)

**Comment by hanbyul-here** [comment]
@xuv please let me know if you find out anything! I am super interested in knowing why :(

**Comment by xuv** [comment]
@hanbyul-here Hey. Have been working on the problem. I solved the `ERROR in Path must be string` by updating some dependencies (mainly Babel & Webpack). So now the server starts and the webpage displays. But I have some new errors with React. :)
If you want to check it out for yourself, here is my working copy: https://github.com/xuv/tile-exporter/tree/local-node6

**Comment by xuv** [comment]
@hanbyul-here Runs fine locally on node6 now. \o/ Making a pull request. Can you check it out?

**Comment by hanbyul-here** [comment]
closed thanks to @xuv  :)
